Added creation of helper files

diff --git a/spark-make b/spark-make
--- a/spark-make
+++ b/spark-make
@@ -5,14 +5,25 @@ TYPE="$1"
 NAME="$2"
 
 if [ -z "$TYPE" ] || [ -z "$NAME" ]; then
-    echo "Usage: spark-make [controller|model|seeder|migration|command|filter] Name"
+    echo "Usage: spark-make [controller|model|seeder|migration|command|filter|helper] Name"
+    echo "No need for extension, just the name. For helpers, do not include _helper."
     exit 1
 fi
 
-php spark make:$TYPE "$NAME"
+if [[ ! "$TYPE" =~ ^(controller|model|seeder|migration|command|filter|helper)$ ]]; then
+    echo "Invalid type. Must be one of: controller, model, seeder, migration, command, filter, helper"
+    exit 1
+fi
 
-# Convert first letter to uppercase for filename
-FILE_NAME="$(tr '[:lower:]' '[:upper:]' <<< ${NAME:0:1})${NAME:1}.php"
+# If anything other then helper is requested, use spark make command
+if [[ "$TYPE" != "helper" ]]; then
+    php spark make:$TYPE "$NAME"
+    # Convert first letter to uppercase for filename
+    FILE_NAME="$(tr '[:lower:]' '[:upper:]' <<< ${NAME:0:1})${NAME:1}.php"
+else
+    # For helper, just open the file directly
+    FILE_NAME="${NAME}_helper.php"
+fi
 
 case "$TYPE" in
     seeder)
@@ -33,6 +44,10 @@ case "$TYPE" in
         ;;
     command)
         FILE="app/Commands/$FILE_NAME"
+        ;;
+    helper)
+        FILE="app/Helpers/$FILE_NAME"
+        touch "$FILE"  # Create the helper file
         ;;
     *)
         FILE=""
